In [108]:
## Required Libraries
import pandas as pd
import numpy as np

In [109]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\abc\anaconda3\lib\site-packages (26.7.0)

In [110]:
import mysql.connector

In [111]:
## Connector create
connection=mysql.connector.connect(
host='localhost',
user='root',
password='SQL20july@78',
database='ecommerce_analytics'
)

In [112]:
print(connection.is_connected())

True

In [113]:
## cursor create
cursor =connection.cursor()

In [114]:
query ='select* from customers limit 10'

In [115]:
cursor.execute(query)

In [116]:
results = cursor.fetchall()

In [117]:
print(results)

[('C0001', 'Customer_0001', 'Male', 34, 'Mumbai', 'West', datetime.date(2023, 1, 21)), ('C0002', 'Customer_0002', 'Female', 26, 'Hyderabad', 'South', datetime.date(2025, 9, 10)), ('C0003', 'Customer_0003', 'Male', 50, 'Pune', 'West', datetime.date(2023, 11, 1)), ('C0004', 'Customer_0004', 'Male', 37, 'Bengaluru', 'South', datetime.date(2024, 1, 6)), ('C0005', 'Customer_0005', 'Male', 30, 'Chennai', 'South', datetime.date(2025, 5, 2)), ('C0006', 'Customer_0006', 'Female', 45, 'Jaipur', 'North', datetime.date(2024, 1, 19)), ('C0007', 'Customer_0007', 'Male', 46, 'Lucknow', 'North', datetime.date(2024, 3, 20)), ('C0008', 'Customer_0008', 'Male', 30, 'Bengaluru', 'South', datetime.date(2024, 2, 29)), ('C0009', 'Customer_0009', 'Male', 52, 'Hyderabad', 'South', datetime.date(2023, 6, 10)), ('C0010', 'Customer_0010', 'Female', 23, 'Ahmedabad', 'West', datetime.date(2024, 9, 20))]

In [118]:
customers=pd.read_sql('select * from customers', connection)

C:\Users\ABC\AppData\Local\Temp\ipykernel_6804\3072969647.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers=pd.read_sql('select * from customers', connection)

In [119]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   object
 1   CustomerName  1000 non-null   object
 2   Gender        1000 non-null   object
 3   Age           1000 non-null   int64
 4   City          1000 non-null   object
 5   Region        1000 non-null   object
 6   SignupDate    1000 non-null   object
dtypes: int64(1), object(6)
memory usage: 54.8+ KB

In [120]:
customers.head()

  CustomerID   CustomerName  Gender  Age       City Region  SignupDate
0      C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1      C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2      C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3      C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4      C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [121]:
customers.tail()

    CustomerID   CustomerName  Gender  Age       City Region  SignupDate
995      C0996  Customer_0996    Male   34    Lucknow  North  2025-04-19
996      C0997  Customer_0997    Male   46     Jaipur  North  2024-06-02
997      C0998  Customer_0998  Female   25  Ahmedabad   West  2024-01-10
998      C0999  Customer_0999  Female   32    Chennai  South  2024-03-26
999      C1000  Customer_1000    Male   44    Lucknow  North  2025-10-11

In [122]:
customers.isnull().sum()

CustomerID      0
CustomerName    0
Gender          0
Age             0
City            0
Region          0
SignupDate      0
dtype: int64

In [123]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   object
 1   CustomerName  1000 non-null   object
 2   Gender        1000 non-null   object
 3   Age           1000 non-null   int64
 4   City          1000 non-null   object
 5   Region        1000 non-null   object
 6   SignupDate    1000 non-null   object
dtypes: int64(1), object(6)
memory usage: 54.8+ KB

In [124]:
products=pd.read_sql('select * from products',  connection)
orders=pd.read_sql('select * from orders', connection)
returns=pd.read_sql('select * from returns', connection)
order_details=pd.read_sql('select * from orderDetails', connection)

C:\Users\ABC\AppData\Local\Temp\ipykernel_6804\3454041284.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products=pd.read_sql('select * from products',  connection)
C:\Users\ABC\AppData\Local\Temp\ipykernel_6804\3454041284.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders=pd.read_sql('select * from orders', connection)
C:\Users\ABC\AppData\Local\Temp\ipykernel_6804\3454041284.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  returns=pd.read_sql('select * from returns', connection)
C:\Users\ABC\AppData\Local\Temp\ipykernel_6804\3454041284.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  order_details=pd.read_sql('select * from orderDetails', connection)

In [125]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Returns:" ,returns.shape)
print("Order_Details", order_details.shape)

Customers: (1000, 7)
Products: (82, 5)
Orders: (5000, 5)
Returns: (257, 4)
Order_Details (12558, 8)

In [126]:
cursor.close()
connection.close()

## DataFrames Check

In [127]:
customers.shape

(1000, 7)

In [128]:
products.shape

(82, 5)

In [129]:
orders.shape

(5000, 5)

In [130]:
order_details.shape

(12558, 8)

In [131]:
returns.shape

(257, 4)

##  Top 5 Values Records

In [132]:
customers.head()

  CustomerID   CustomerName  Gender  Age       City Region  SignupDate
0      C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1      C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2      C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3      C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4      C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [133]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   object
 1   CustomerName  1000 non-null   object
 2   Gender        1000 non-null   object
 3   Age           1000 non-null   int64
 4   City          1000 non-null   object
 5   Region        1000 non-null   object
 6   SignupDate    1000 non-null   object
dtypes: int64(1), object(6)
memory usage: 54.8+ KB

In [134]:
customers['SignupDate']=pd.to_datetime(customers['SignupDate'])

In [135]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   object
 1   CustomerName  1000 non-null   object
 2   Gender        1000 non-null   object
 3   Age           1000 non-null   int64
 4   City          1000 non-null   object
 5   Region        1000 non-null   object
 6   SignupDate    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 54.8+ KB

In [136]:
customers.duplicated().sum()

np.int64(0)

In [137]:
customers.isnull().sum()

CustomerID      0
CustomerName    0
Gender          0
Age             0
City            0
Region          0
SignupDate      0
dtype: int64

In [138]:
products.head()

  ProductID          ProductName     Category  CostPrice  SellingPrice
0     P0001  Wireless Headphones  Electronics     4840.0        8847.0
1     P0002  Wireless Headphones  Electronics     4745.0        8892.0
2     P0003  Wireless Headphones  Electronics      262.0         319.0
3     P0004          Smart Watch  Electronics     2528.0        3517.0
4     P0005          Smart Watch  Electronics      289.0         526.0

In [139]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     82 non-null     object
 1   ProductName   82 non-null     object
 2   Category      82 non-null     object
 3   CostPrice     82 non-null     float64
 4   SellingPrice  82 non-null     float64
dtypes: float64(2), object(3)
memory usage: 3.3+ KB

In [140]:
products.duplicated().sum()

np.int64(0)

In [141]:
orders.head()

  OrderID   OrderDate CustomerID PaymentMethod OrderStatus
0  O00001  2026-01-19      C0484           UPI   Delivered
1  O00002  2026-02-14      C0450   Credit Card   Delivered
2  O00003  2025-11-21      C0523   Credit Card   Delivered
3  O00004  2025-05-08      C0871           UPI   Delivered
4  O00005  2025-05-04      C0354   Net Banking   Delivered

In [142]:
orders['OrderDate']=pd.to_datetime(orders['OrderDate'])

In [143]:
orders.duplicated().sum()
orders.isnull().sum()
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        5000 non-null   object
 1   OrderDate      5000 non-null   datetime64[ns]
 2   CustomerID     5000 non-null   object
 3   PaymentMethod  5000 non-null   object
 4   OrderStatus    5000 non-null   object
dtypes: datetime64[ns](1), object(4)
memory usage: 195.4+ KB

In [144]:
order_details.head()

,orderDetailID,OrderID,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit
0,OD000001,O00001,P0014,4,10018.0,15.0,34061.20,12649.20
1,OD000002,O00001,P0063,3,5568.0,5.0,15868.80,6532.80
2,OD000003,O00002,P0030,1,10331.0,5.0,9814.45,3909.45
3,OD000004,O00002,P0027,4,4363.0,10.0,15706.80,2006.80
4,OD000005,O00003,P0040,2,6601.0,5.0,12541.90,4543.90

In [145]:
order_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12558 entries, 0 to 12557
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   orderDetailID  12558 non-null  object
 1   OrderID        12558 non-null  object
 2   ProductID      12558 non-null  object
 3   Quantity       12558 non-null  int64
 4   UnitPrice      12558 non-null  float64
 5   DiscountPct    12558 non-null  float64
 6   SalesAmount    12558 non-null  float64
 7   Profit         12558 non-null  float64
dtypes: float64(4), int64(1), object(3)
memory usage: 785.0+ KB

In [146]:
order_details.duplicated().sum()

np.int64(0)

In [147]:
returns.head()
returns["ReturnDate"]=pd.to_datetime(returns["ReturnDate"])

In [148]:
returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ReturnID      257 non-null    object
 1   OrderID       257 non-null    object
 2   ReturnDate    257 non-null    datetime64[ns]
 3   ReturnReason  257 non-null    object
dtypes: datetime64[ns](1), object(3)
memory usage: 8.2+ KB

In [149]:
returns.isnull().sum()

ReturnID        0
OrderID         0
ReturnDate      0
ReturnReason    0
dtype: int64

In [150]:
returns.duplicated().sum()

np.int64(0)

## Data Type

In [151]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   object
 1   CustomerName  1000 non-null   object
 2   Gender        1000 non-null   object
 3   Age           1000 non-null   int64
 4   City          1000 non-null   object
 5   Region        1000 non-null   object
 6   SignupDate    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 54.8+ KB

## Primary Key Duplicate Check

In [152]:
customers['CustomerID'].duplicated().sum()

np.int64(0)

In [153]:

products.isnull().sum()
products['ProductID'].duplicated().sum()

np.int64(0)

In [154]:
orders['OrderID'].duplicated().sum()

np.int64(0)

In [155]:
order_details['orderDetailID'].duplicated().sum()

np.int64(0)

In [156]:
returns['ReturnID'].duplicated().sum()

np.int64(0)

In [157]:
## Numeric Value Check
order_details.describe()

           Quantity     UnitPrice   DiscountPct   SalesAmount        Profit
count  12558.000000  12558.000000  12558.000000  12558.000000  12558.000000
mean       2.501752   6272.299570     10.742156  14010.138708   4804.382457
std        1.119501   3461.536155      7.112802  10628.052040   4894.725391
min        1.000000    319.000000      0.000000    239.250000  -2048.000000
25%        2.000000   3416.000000      5.000000   5949.000000   1342.400000
50%        2.000000   6288.000000     10.000000  11210.400000   3215.600000
75%        4.000000   8847.000000     15.000000  20044.800000   6608.400000
max        4.000000  14270.000000     25.000000  57080.000000  30860.000000

In [158]:
# Impossible Value Check
order_details[order_details["Quantity"] <=0]

Empty DataFrame
Columns: [orderDetailID, OrderID, ProductID, Quantity, UnitPrice, DiscountPct, SalesAmount, Profit]
Index: []

In [159]:
order_details[(order_details["DiscountPct"] < 0) | (order_details['DiscountPct'] >100)]

Empty DataFrame
Columns: [orderDetailID, OrderID, ProductID, Quantity, UnitPrice, DiscountPct, SalesAmount, Profit]
Index: []

In [160]:
order_details[order_details["SalesAmount"] < 0]

Empty DataFrame
Columns: [orderDetailID, OrderID, ProductID, Quantity, UnitPrice, DiscountPct, SalesAmount, Profit]
Index: []

In [161]:
# Customer Age Validation
customers[(customers["Age"] <18) | (customers["Age"]>100)]

Empty DataFrame
Columns: [CustomerID, CustomerName, Gender, Age, City, Region, SignupDate]
Index: []

In [162]:
# Create Analytics Dataset

df=orders.merge(
    customers,
    on='CustomerID',
    how="left"
)

In [163]:
## Add OrderDetals

df=df.merge(
    order_details,
    on="OrderID",
    how='inner'
)

In [164]:
# Add Product Information

df=df.merge(
    products,
    on="ProductID",
    how="left"
)

In [165]:
df.shape

(12558, 22)

In [166]:
df.head()

,OrderID,OrderDate,CustomerID,PaymentMethod,OrderStatus,CustomerName,Gender,Age,City,Region,...,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit,ProductName,Category,CostPrice,SellingPrice
0,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,...,P0014,4,10018.0,15.0,34061.20,12649.20,Mouse,Electronics,5353.0,10018.0
1,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,...,P0063,3,5568.0,5.0,15868.80,6532.80,Shampoo,Beauty,3112.0,5568.0
2,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,...,P0030,1,10331.0,5.0,9814.45,3909.45,Table Lamp,Home,5905.0,10331.0
3,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,...,P0027,4,4363.0,10.0,15706.80,2006.80,Air Fryer,Home,3425.0,4363.0
4,O00003,2025-11-21,C0523,Credit Card,Delivered,Customer_0523,Female,60,Delhi,North,...,P0040,2,6601.0,5.0,12541.90,4543.90,T-Shirt,Fashion,3999.0,6601.0

In [170]:
df['Year']=df["OrderDate"].dt.year
df['Month']=df["OrderDate"].dt.month
df['MonthName']=df["OrderDate"].dt.month_name()
df['YearMonth']=df["OrderDate"].dt.to_period('M').astype(str)

In [172]:
## Profit Margin

df["ProfitMarginPct"]=(
    df["Profit"]/df["SalesAmount"]
)*100

In [ ]:
## Data Quality Check

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12558 entries, 0 to 12557
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          12558 non-null  object
 1   OrderDate        12558 non-null  datetime64[ns]
 2   CustomerID       12558 non-null  object
 3   PaymentMethod    12558 non-null  object
 4   OrderStatus      12558 non-null  object
 5   CustomerName     12558 non-null  object
 6   Gender           12558 non-null  object
 7   Age              12558 non-null  int64
 8   City             12558 non-null  object
 9   Region           12558 non-null  object
 10  SignupDate       12558 non-null  datetime64[ns]
 11  orderDetailID    12558 non-null  object
 12  ProductID        12558 non-null  object
 13  Quantity         12558 non-null  int64
 14  UnitPrice        12558 non-null  float64
 15  DiscountPct      12558 non-null  float64
 16  SalesAmount      12558 non-null  float64
 17  Profit           12558 non-null  float64
 18  ProductName      12558 non-null  object
 19  Category         12558 non-null  object
 20  CostPrice        12558 non-null  float64
 21  SellingPrice     12558 non-null  float64
 22  Year             12558 non-null  int32
 23  Month            12558 non-null  int32
 24  MonthName        12558 non-null  object
 25  YearMonth        12558 non-null  object
 26  ProfitMarginPct  12558 non-null  float64
dtypes: datetime64[ns](2), float64(7), int32(2), int64(2), object(14)
memory usage: 2.5+ MB

In [175]:
df.isnull().sum()

OrderID            0
OrderDate          0
CustomerID         0
PaymentMethod      0
OrderStatus        0
CustomerName       0
Gender             0
Age                0
City               0
Region             0
SignupDate         0
orderDetailID      0
ProductID          0
Quantity           0
UnitPrice          0
DiscountPct        0
SalesAmount        0
Profit             0
ProductName        0
Category           0
CostPrice          0
SellingPrice       0
Year               0
Month              0
MonthName          0
YearMonth          0
ProfitMarginPct    0
dtype: int64

In [176]:
df.duplicated().sum()

np.int64(0)

In [177]:
df.to_csv("ecommerce_clean_data.csv",index=False)

In [171]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'PaymentMethod', 'OrderStatus',
       'CustomerName', 'Gender', 'Age', 'City', 'Region', 'SignupDate',
       'orderDetailID', 'ProductID', 'Quantity', 'UnitPrice', 'DiscountPct',
       'SalesAmount', 'Profit', 'ProductName', 'Category', 'CostPrice',
       'SellingPrice', 'Year', 'Month', 'MonthName', 'YearMonth'],
      dtype='object')

In [169]:
## Check Duplicate Order Details
df["orderDetailID"].duplicated().sum()

np.int64(0)